# https://ci.appveyor.com/project/jakubroztocil/httpie
build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
  - "git config --global user.email 'foo@example.com'"
  - "git config --global user.name 'foo'"
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install pyflakes"
  - "%PYTHON%/python.exe setup.py make_versioneer"
test_script:
  - "%PYTHON%/python.exe test/test_git.py"
  - "%PYTHON%/python.exe setup.py make_long_version_py_git"
  - "%PYTHON%/Scripts/pyflakes.exe setup.py versioneer.py git_version.py"
  - "%PYTHON%/Scripts/pyflakes.exe test src/subprocess_helper.py src/git/from_keywords.py"